// Writes the build stamp the footer shows.
//
// There is no bundler here, so nothing injects a version at build time. Run
// this before committing a deploy: `npm run stamp`.
//
// The point is answering "what were you running?" when somebody reports a
// problem. A date alone is ambiguous when two deploys land in a day, and a
// commit alone means nothing to the person reporting, so it records both.
//
// The SHA is HEAD at stamp time, which is the commit this build was made FROM
// -- the stamped file itself lands in the next commit. That is one hop off and
// still identifies the code exactly, because the only thing that changed
// between them is this stamp.

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const sha = (() => {
    try {
        return execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
    } catch {
        return 'unknown';
    }
})();

const built = new Date().toISOString().replace(/\.\d+Z$/, 'Z');

writeFileSync(
    new URL('../js/version.js', import.meta.url),
    `// Generated by tools/stamp.mjs. Do not edit by hand.\n` +
        `export const BUILD = ${JSON.stringify({ sha, built })};\n`
);

console.log(`stamped ${sha} at ${built}`);
